<?xml version="1.0"?>
<package format="2">

  <name>pairs_uav_trackers</name>
  <version>1.0.0</version>
  <description>PAIRS UAV tracker plugins — MPC tracker, line tracker, landoff tracker, speed tracker, flip tracker</description>

  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>

  <license>BSD 3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cmake_modules</depend>
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>pluginlib</depend>
  <depend>geometry_msgs</depend>
  <depend>tf</depend>
  <depend>std_msgs</depend>
  <depend>pairs_lib</depend>
  <depend>pairs_msgs</depend>
  <depend>pairs_uav_managers</depend>
  <depend>dynamic_reconfigure</depend>
  <depend>pairs_uav_testing</depend>

  <export>
    <pairs_uav_managers plugin="${prefix}/plugins.xml" />
  </export>

</package>
